### ISSUE TITLE
other_image unused in mnist example

### ISSUE THREAD

**Issue by Saahil-Agr** [google-deepmind/uncertain_ground_truth#1]
In the `Data` section in `colab_mnist_multi_label.ipynb` it seems like while generating samples from the data, other_images are being created but not being used anywhere? Was this supposed to be added to the `combined_images` in line 15? The way it is implemented currently, the `other_image` seems redundant. Is there a specific reason the `other_image` is being generated?

**Comment by davidstutz** [comment]
Hi, well spotted. I just double-checked and `other_image` seems to be left over fro debugging. The images in `combined_images` look as expected and reflect the experiments in the paper. For example:

![image](https://github.com/google-deepmind/uncertain_ground_truth/assets/1203091/be47dac6-03f5-474d-99eb-dae46ebb3940)
