### ISSUE TITLE
Incorrect OpenReview Link in README

### ISSUE THREAD

**Issue by ceziegler** [google-deepmind/uncertain_ground_truth#2]
Just FYI. Reference 1 in README has an invalid link. [correct link](https://arxiv.org/pdf/2307.09302.pdf)

**Comment by davidstutz** [comment]
Thanks for checking, but works fine for me - [1] is the OpenReview TMLR version of the paper which is identical with the ArXiv link you shared.

[1] https://openreview.net/forum?id=CAd6V2qXxc
